name: Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: toasted-mudlet/ci-templates/.github/workflows/lua-release.yml@main
